# Pandas

data analysis library

series - single dimension

Data Frame - Multi dimensional

In [121]:
import pandas as pd

# Series in Pandas

In [122]:
s1 = pd.Series([1,2,3,4])
s1

0    1
1    2
2    3
3    4
dtype: int64

In [123]:
type(s1)

pandas.core.series.Series

In [124]:
s1.index = ["one" , "two" , "three" , "four"]

s1

one      1
two      2
three    3
four     4
dtype: int64

In [125]:
s1.index

Index(['one', 'two', 'three', 'four'], dtype='object')

In [126]:
s2 = pd.Series([34 , 89 ,43 ,90 , 45 ,23 ,32 , 89 ,12] , index = ["a", "b","c","d" ,"e" ,"x" , "g" , "h" , "i" ])
s2

a    34
b    89
c    43
d    90
e    45
x    23
g    32
h    89
i    12
dtype: int64

In [127]:
s2["a"]

34

In [128]:
s1 = s1 * 5
s1

one       5
two      10
three    15
four     20
dtype: int64

# Adding series 01 and series 02

In [129]:
s1 + s2

a       NaN
b       NaN
c       NaN
d       NaN
e       NaN
four    NaN
g       NaN
h       NaN
i       NaN
one     NaN
three   NaN
two     NaN
x       NaN
dtype: float64

In [130]:
s2 = pd.Series([34 , 89 ,43 ,90 , 45 ,23 ,32 , 89 ,12] , index = ["one", "two","c","d" ,"e" ,"x" , "g" , "h" , "i" ])
s2


one    34
two    89
c      43
d      90
e      45
x      23
g      32
h      89
i      12
dtype: int64

In [131]:
s1

one       5
two      10
three    15
four     20
dtype: int64

In [132]:
s1+s2

c         NaN
d         NaN
e         NaN
four      NaN
g         NaN
h         NaN
i         NaN
one      39.0
three     NaN
two      99.0
x         NaN
dtype: float64

In [133]:
# An axample from numpy Arrays
import numpy as np
numPy = np.arange(9).reshape(3,3)
numPy


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [134]:
s2

one    34
two    89
c      43
d      90
e      45
x      23
g      32
h      89
i      12
dtype: int64

In [135]:
SeriesExample = pd.Series([40 ,12 ,42, 33,94, 65 ] , index=["Ahmed" , "Ali" , "Faisal" , "Akbar" , "Saleem" , "Daniyal"])

SeriesExample

Ahmed      40
Ali        12
Faisal     42
Akbar      33
Saleem     94
Daniyal    65
dtype: int64

In [136]:
SeriesExample.apply(lambda x:x*10) # we have performed the operation of multiplication and addition on it

Ahmed      400
Ali        120
Faisal     420
Akbar      330
Saleem     940
Daniyal    650
dtype: int64

In [137]:
data = SeriesExample.apply(lambda x: np.where(x>50 , "pass" , "fail"))
data

Ahmed      fail
Ali        fail
Faisal     fail
Akbar      fail
Saleem     pass
Daniyal    pass
dtype: object

In [138]:
s5 = pd.Series([1 , 2, 3 ,4 ,5] , index=["a" , "b" , "c" , "d" , "e"])
s5

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [139]:
s6 = pd.Series(145 , index = ["a" , "b" , "c"])
s6


a    145
b    145
c    145
dtype: int64

In [140]:
import numpy as np
zeros = np.zeros(10).reshape(5,2)
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [141]:
np.linspace(0 ,10 ,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [142]:
data.value_counts()

fail    4
pass    2
dtype: int64

If I want to get the data in pandas then,

In [143]:
data

Ahmed      fail
Ali        fail
Faisal     fail
Akbar      fail
Saleem     pass
Daniyal    pass
dtype: object

In [144]:
data[['Ahmed' , "Ali" , "Akbar" , "Saleem"]]

Ahmed     fail
Ali       fail
Akbar     fail
Saleem    pass
dtype: object

In [145]:
# data

data_with_nan = pd.Series([10 , 12 , 45 , np.nan])

data_with_nan

0    10.0
1    12.0
2    45.0
3     NaN
dtype: float64

In [146]:
values = pd.Series([0 , 12])
values

0     0
1    12
dtype: int64

# Pandas Data Frame

In [147]:
# First I have to create a dictionary here:-

student = {

           'Name' : ["Ali" , "Owais" , "Hamza"],
           'Mode' : ["Online " , "Onsite" , "Online"],
           'courses' : [ "PIAIC" , "SMIT" , "Both"]

}

In [148]:
student

{'Name': ['Ali', 'Owais', 'Hamza'],
 'Mode': ['Online ', 'Onsite', 'Online'],
 'courses': ['PIAIC', 'SMIT', 'Both']}

In [149]:
# Now I have to create a data frame from this dictionary

df = pd.DataFrame(student)
df

Name     Mode courses
0    Ali  Online    PIAIC
1  Owais   Onsite    SMIT
2  Hamza   Online    Both

In [150]:
# Series is a single dimension

pd.Series([12 , 13 ,14 ,15, 16]) # This is a single Dimension Data

# While, DataFrame is a multi dimension

pd.DataFrame([[34 , 45 , 56 ,23 ,56] , [34 ,12 , 34 ,13 , 90]])



0   1   2   3   4
0  34  45  56  23  56
1  34  12  34  13  90

# Create a list in pandas and then provide them the index values

In [151]:
list = [[45 , 89 , 23 , 84 , 342 ] , [45 , 89 , 23 , 84 , 342 ], [45 , 89 , 23 , 84 , 342 ] , [45 , 89 , 23 , 84 , 342 ] , [45 , 89 , 23 , 84 , 342 ]]
list


[[45, 89, 23, 84, 342],
 [45, 89, 23, 84, 342],
 [45, 89, 23, 84, 342],
 [45, 89, 23, 84, 342],
 [45, 89, 23, 84, 342]]

In [152]:
# Now create a data frame from this list

pd.DataFrame(list , index = [1 , 2 , 3 , 4 , 5] , columns = ["a" , "b" , "c" , "d" , "e"])




a   b   c   d    e
1  45  89  23  84  342
2  45  89  23  84  342
3  45  89  23  84  342
4  45  89  23  84  342
5  45  89  23  84  342

# Accessing the Data Now

In [153]:
SeriesExample = pd.Series(["Ahmed" , "Ali" , "Faisal" , "Akbar" , "Saleem" , "Daniyal"] , index=[ 1, 2 ,3 , 4 ,5 ,6 ])

SeriesExample

1      Ahmed
2        Ali
3     Faisal
4      Akbar
5     Saleem
6    Daniyal
dtype: object

In [183]:

student = {
            "Roll_Numbers" : [20 ,34 ,78 ,54 , 82 ,13],
           'Name' : ["Ali" , "Owais" , "Hamza" , "Fakhar" , "Saim" , "Hammad"],
           'Mode' : ["Online " , "Onsite" , "Online","Online " , "Onsite" , "Online"],
           'courses' : [ "PIAIC" , "SMIT" , "Both" , "PIAIC" , "SMIT" , "Both"],
           'Gender' : ['Male' , 'Male' , 'Male','Male' , 'Male' , 'Male'],
           'Age' : [45 , 23 , 12 , 89 ,65 ,34],
           'Status' : [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]

}

In [184]:
student

{'Roll_Numbers': [20, 34, 78, 54, 82, 13],
 'Name': ['Ali', 'Owais', 'Hamza', 'Fakhar', 'Saim', 'Hammad'],
 'Mode': ['Online ', 'Onsite', 'Online', 'Online ', 'Onsite', 'Online'],
 'courses': ['PIAIC', 'SMIT', 'Both', 'PIAIC', 'SMIT', 'Both'],
 'Gender': ['Male', 'Male', 'Male', 'Male', 'Male', 'Male'],
 'Age': [45, 23, 12, 89, 65, 34],
 'Status': [nan, nan, nan, nan, nan, nan]}

In [185]:
data = pd.DataFrame(student)
data

Roll_Numbers    Name     Mode courses Gender  Age  Status
0            20     Ali  Online    PIAIC   Male   45     NaN
1            34   Owais   Onsite    SMIT   Male   23     NaN
2            78   Hamza   Online    Both   Male   12     NaN
3            54  Fakhar  Online    PIAIC   Male   89     NaN
4            82    Saim   Onsite    SMIT   Male   65     NaN
5            13  Hammad   Online    Both   Male   34     NaN

In [186]:
data['Status'] = ["Passed" if age<50 else "Fail" for age in data["Age"]]

data

Roll_Numbers    Name     Mode courses Gender  Age  Status
0            20     Ali  Online    PIAIC   Male   45  Passed
1            34   Owais   Onsite    SMIT   Male   23  Passed
2            78   Hamza   Online    Both   Male   12  Passed
3            54  Fakhar  Online    PIAIC   Male   89    Fail
4            82    Saim   Onsite    SMIT   Male   65    Fail
5            13  Hammad   Online    Both   Male   34  Passed

Add a new column in our DataFrame through pandas

In [187]:
data["City"] = data["Mode"].apply(lambda x: 'Karachi ' if x == "Onsite" else "Outside Khi")

data

Roll_Numbers    Name     Mode courses Gender  Age  Status         City
0            20     Ali  Online    PIAIC   Male   45  Passed  Outside Khi
1            34   Owais   Onsite    SMIT   Male   23  Passed     Karachi 
2            78   Hamza   Online    Both   Male   12  Passed  Outside Khi
3            54  Fakhar  Online    PIAIC   Male   89    Fail  Outside Khi
4            82    Saim   Onsite    SMIT   Male   65    Fail     Karachi 
5            13  Hammad   Online    Both   Male   34  Passed  Outside Khi

In [188]:
def Age_Func(Age):
  if Age<20:
    return ("teenager")
  elif Age<40:
    return ("Young")
  elif Age<60:
    return ("Experience Man")
  elif Age>60:
    return ("retired")

Age_Func(134)

'retired'

In [199]:
data["Age Factor"] = data["Age"].apply(Age_Func)
data

# data.drop("Status_Of_Age" , axis =1 )

Roll_Numbers    Name     Mode courses Gender  Age  Status         City  \
0            20     Ali  Online    PIAIC   Male   45  Passed  Outside Khi   
1            34   Owais   Onsite    SMIT   Male   23  Passed     Karachi    
2            78   Hamza   Online    Both   Male   12  Passed  Outside Khi   
3            54  Fakhar  Online    PIAIC   Male   89    Fail  Outside Khi   
4            82    Saim   Onsite    SMIT   Male   65    Fail     Karachi    
5            13  Hammad   Online    Both   Male   34  Passed  Outside Khi   

       Age Factor  
0  Experience Man  
1           Young  
2        teenager  
3         retired  
4         retired  
5           Young

In [200]:
data

Roll_Numbers    Name     Mode courses Gender  Age  Status         City  \
0            20     Ali  Online    PIAIC   Male   45  Passed  Outside Khi   
1            34   Owais   Onsite    SMIT   Male   23  Passed     Karachi    
2            78   Hamza   Online    Both   Male   12  Passed  Outside Khi   
3            54  Fakhar  Online    PIAIC   Male   89    Fail  Outside Khi   
4            82    Saim   Onsite    SMIT   Male   65    Fail     Karachi    
5            13  Hammad   Online    Both   Male   34  Passed  Outside Khi   

    Status_Of_Age      Age Factor  
0  Experience Man  Experience Man  
1           Young           Young  
2        teenager        teenager  
3         retired         retired  
4         retired         retired  
5           Young           Young

# Map Function in a dictionary

In [214]:
Ages = {

            "Faizan" : 74,

            "Faisal" : 42,

            "Farhan" : 23,

            "Faiz" : 59,

            "Faiza" : 29,


}


In [217]:
data["Map_Ages"] = data["Age"].map(Ages)
data

Roll_Numbers    Name     Mode courses Gender  Age  Status         City  \
0            20     Ali  Online    PIAIC   Male   45  Passed  Outside Khi   
1            34   Owais   Onsite    SMIT   Male   23  Passed     Karachi    
2            78   Hamza   Online    Both   Male   12  Passed  Outside Khi   
3            54  Fakhar  Online    PIAIC   Male   89    Fail  Outside Khi   
4            82    Saim   Onsite    SMIT   Male   65    Fail     Karachi    
5            13  Hammad   Online    Both   Male   34  Passed  Outside Khi   

    Status_Of_Age      Age Factor  Map_Ages  
0  Experience Man  Experience Man       NaN  
1           Young           Young       NaN  
2        teenager        teenager       NaN  
3         retired         retired       NaN  
4         retired         retired       NaN  
5           Young           Young       NaN

In [222]:
data.to_excel("Student_Data-Complete_Pandas_PIAIC.xlsx")

In [223]:
# If you ever want to read the data of any file then

toyota_DataSet = pd.read_csv("/content/ToyotaCorolla.csv")

toyota_DataSet

Id                                              Model  Price  \
0        1      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13500   
1        2      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13750   
2        3      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  13950   
3        4      TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  14950   
4        5        TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  13750   
...    ...                                                ...    ...   
1431  1438         TOYOTA Corolla 1.3 16V HATCHB G6 2/3-Doors   7500   
1432  1439  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...  10845   
1433  1440  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   8500   
1434  1441  TOYOTA Corolla 1.3 16V HATCHB LINEA TERRA 2/3-...   7250   
1435  1442        TOYOTA Corolla 1.6 LB LINEA TERRA 4/5-Doors   6950   

      Age_08_04  Mfg_Month  Mfg_Year     KM Fuel_Type   HP  Met_Color  ...  \
0            23         10      2002  46986    Diesel   90          1  ...   
1            23         10      2002  72937    Diesel   90          1  ...   
2            24          9      2002  41711    Diesel   90          1  ...   
3            26          7      2002  48000    Diesel   90          0  ...   
4            30          3      2002  38500    Diesel   90          0  ...   
...         ...        ...       ...    ...       ...  ...        ...  ...   
1431         69         12      1998  20544    Petrol   86          1  ...   
1432         72          9      1998  19000    Petrol   86          0  ...   
1433         71         10      1998  17016    Petrol   86          0  ...   
1434         70         11      1998  16916    Petrol   86          1  ...   
1435         76          5      1998      1    Petrol  110          0  ...   

     Powered_Windows  Power_Steering  Radio  Mistlamps  Sport_Model  \
0                  1               1      0          0            0   
1                  0               1      0          0            0   
2                  0               1      0          0            0   
3                  0               1      0          0            0   
4                  1               1      0          1            0   
...              ...             ...    ...        ...          ...   
1431               1               1      0          1            1   
1432               0               1      0          0            1   
1433               0               1      0          0            0   
1434               0               0      0          0            0   
1435               0               1      0          0            0   

      Backseat_Divider  Metallic_Rim  Radio_cassette  Parking_Assistant  \
0                    1             0               0                  0   
1                    1             0               0                  0   
2                    1             0               0                  0   
3                    1             0               0                  0   
4                    1             0               0                  0   
...                ...           ...             ...                ...   
1431                 1             0               0                  0   
1432                 1             0               0                  0   
1433                 1             0               0                  0   
1434                 1             0               0                  0   
1435                 0             0               0                  0   

      Tow_Bar  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1431        0  
1432        0  
1433        0  
1434        0  
1435        0  

[1436 rows x 39 columns]

---
# Successfully revised complete Class # 02 of PIAIC Quarter 02 Batch: 36 AIC
---