# NumPy

In [ ]:
# NumPy is Numerical Python , it is used to create arrays in python

In [2]:
# Importing Numpy
import numpy as np

# create an array:

arr = np.array([45 , 55 ,65 , 75])
arr

array([45, 55, 65, 75])

In [ ]:
# If I wanna see the size of it , then

size = arr.size
size

4

In [ ]:
# The array is 1 dimensional , which we can see here
arr.ndim

1

In [ ]:
arr

array([45, 55, 65, 75])

In [ ]:
# 1D = vector
# 2D = matrix
# 3D = cube
# .
# .
# .
# nD = ....

arr.shape

(4,)

In [ ]:
# You can also create an array using this below method:

array = np.arange(0,20)
array # An array from numbers 0 to 20

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# Let's talk about 2D array

arr2D = np.array([[34 , 56 , 42] , [23 , 90 , 12] , [43 , 90 , 41] , [87 , 56 ,34]])
arr2D #This is two dimensional array

array([[34, 56, 42],
       [23, 90, 12],
       [43, 90, 41],
       [87, 56, 34]])

In [ ]:
arr2D = np.arange(0,20).reshape(1,20)
arr2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [ ]:
arr2D = np.arange(20)
arr2D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2D.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
arr2D.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# This is a scalar quanitity , so the number has no direction

arr = np.array(10)
arr

array(10)

In [ ]:
# arr.shape
arr.ndim

0

In [ ]:
arr = np.array([10])
arr

array([10])

In [ ]:
arr.shape

(1,)

In [ ]:
arr.ndim

1

In [ ]:
arr = np.array([[10] , [78] , [89]])
arr

array([[10],
       [78],
       [89]])

In [ ]:
arr.ndim # Because this is a 2D dimension array

2

In [17]:
# 2D Array

# arr2D = np.array([[10 , 89 , 34 , 14 , 59 , 42 , 23 , 52 , 43 , 12 , 53 , 123 , 90 ,12 , 42]])
arr2D = np.array([[32]])
arr2D

array([[32]])

In [21]:
# Program of loop in python

list = []

for i in range(10):
  i_values = i+1
  list.append(i*2)

print(i_values)
print(list)

10
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [31]:
arr2d = np.arange(1,11)
arr2d



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr2d*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# Adding 02 Matrices

In [35]:
matrix1 = np.arange(25)
matrix1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
matrix2 = np.arange(25,50).reshape(5,5)
matrix2  # matrix has 05 rows and 05 columns

# This technique is called as mirroring or element wise matrix operation

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [39]:
matrix2.shape

(25,)

In [40]:
matrix1.shape

(25,)

In [41]:
matrix1 + matrix2

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57,
       59, 61, 63, 65, 67, 69, 71, 73])

# Array Slicing

In [47]:
# array([row , column] , [row , column])

arr = np.arange(1, 26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
arr[2 , 3] # rows and columns

14

In [56]:
arr[0 , 4]

5

# Array Masking

In [58]:
mask = arr > 5
mask

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [60]:
arr[mask] # it will fetch all the values havign positive values

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25])

In [63]:
arr[arr>20]

array([30, 30, 30, 30, 30])

In [65]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 30, 30, 30, 30, 30])

In [70]:
np.where(arr>2 , 34 , arr )

array([[ 1,  2, 34, 34, 34],
       [34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34]])

# Combining or Concatenating two different Arrays

In [74]:
a = np.arange(1, 51).reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [77]:
b = np.arange(101,151).reshape(10,5)
b

array([[101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145],
       [146, 147, 148, 149, 150]])

In [80]:
# concatenating two differnent arrays

np.concatenate((a,b))
# by default it concatenates with rows , i.e axis = 0

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145],
       [146, 147, 148, 149, 150]])

In [82]:
np.concatenate((a,b) , axis = 1) # Now the code has been concatenated in the form of columns i.e (axis = 1)

array([[  1,   2,   3,   4,   5, 101, 102, 103, 104, 105],
       [  6,   7,   8,   9,  10, 106, 107, 108, 109, 110],
       [ 11,  12,  13,  14,  15, 111, 112, 113, 114, 115],
       [ 16,  17,  18,  19,  20, 116, 117, 118, 119, 120],
       [ 21,  22,  23,  24,  25, 121, 122, 123, 124, 125],
       [ 26,  27,  28,  29,  30, 126, 127, 128, 129, 130],
       [ 31,  32,  33,  34,  35, 131, 132, 133, 134, 135],
       [ 36,  37,  38,  39,  40, 136, 137, 138, 139, 140],
       [ 41,  42,  43,  44,  45, 141, 142, 143, 144, 145],
       [ 46,  47,  48,  49,  50, 146, 147, 148, 149, 150]])

In [83]:
np.stack((a,b)) # stack ka matlb ye hay k , aik k uper aik lagata jaye ga ??

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50]],

       [[101, 102, 103, 104, 105],
        [106, 107, 108, 109, 110],
        [111, 112, 113, 114, 115],
        [116, 117, 118, 119, 120],
        [121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130],
        [131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140],
        [141, 142, 143, 144, 145],
        [146, 147, 148, 149, 150]]])

In [85]:
np.hstack((a,b))

array([[  1,   2,   3,   4,   5, 101, 102, 103, 104, 105],
       [  6,   7,   8,   9,  10, 106, 107, 108, 109, 110],
       [ 11,  12,  13,  14,  15, 111, 112, 113, 114, 115],
       [ 16,  17,  18,  19,  20, 116, 117, 118, 119, 120],
       [ 21,  22,  23,  24,  25, 121, 122, 123, 124, 125],
       [ 26,  27,  28,  29,  30, 126, 127, 128, 129, 130],
       [ 31,  32,  33,  34,  35, 131, 132, 133, 134, 135],
       [ 36,  37,  38,  39,  40, 136, 137, 138, 139, 140],
       [ 41,  42,  43,  44,  45, 141, 142, 143, 144, 145],
       [ 46,  47,  48,  49,  50, 146, 147, 148, 149, 150]])

In [87]:
np.vstack((a,b))

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [101, 102, 103, 104, 105],
       [106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115],
       [116, 117, 118, 119, 120],
       [121, 122, 123, 124, 125],
       [126, 127, 128, 129, 130],
       [131, 132, 133, 134, 135],
       [136, 137, 138, 139, 140],
       [141, 142, 143, 144, 145],
       [146, 147, 148, 149, 150]])

# Some Other Useful Array Methods

In [89]:
a.min()



1

In [95]:
a.argmin()

0

In [97]:
a.argmax()

49